### PR TITLE
Create Tests

### PR DESCRIPTION
**Pull request by ketdougi**
Create tests to ensure modifications/additions don't break current functionality.
#10

### CODE REVIEW

**Review by vijaivir — APPROVED** [review]

**Comment by ketdougi** [comment]
I want to add more tests for two more classes as they seem to hold alot of the functionality but ran into the following challenges:
1. Tests class for ThreadsController- many class members and functions are private making it difficult to test
2. Window- I wasn't sure what else to test in this class
@realjaidhaliwal @OwenBC

**Comment by OwenBC** [comment]
> I want to add more tests for two more classes as they seem to hold alot of the functionality but ran into the following challenges:
> 
> 1. Tests class for ThreadsController- many class members and functions are private making it difficult to test
> 2. Window- I wasn't sure what else to test in this class
>    @realjaidhaliwal @OwenBC

1. This is an issue with how the codebase is structured, it would be better if we had a more divided functionality with a class for a Snake object for example. As it is this entire class handles pretty much all the game logic. Unless we take on the refactoring ourselves, all we can do is test what we can through the public IO of the class. I'd say leave this for now. I've had to rework most of the class to support two players anyway, so I can take on the test suite for this thing.
2. Being a UI class I don't think this class warrants much testing.

**Comment by ketdougi** [comment]
> > I want to add more tests for two more classes as they seem to hold alot of the functionality but ran into the following challenges:
> > 
> > 1. Tests class for ThreadsController- many class members and functions are private making it difficult to test
> > 2. Window- I wasn't sure what else to test in this class
> >    @realjaidhaliwal @OwenBC
> 
> 1. This is an issue with how the codebase is structured, it would be better if we had a more divided functionality with a class for a Snake object for example. As it is this entire class handles pretty much all the game logic. Unless we take on the refactoring ourselves, all we can do is test what we can through the public IO of the class. I'd say leave this for now. I've had to rework most of the class to support two players anyway, so I can take on the test suite for this thing.
> 2. Being a UI class I don't think this class warrants much testing.

Okay sounds good, other then those two the only other class I haven't added anything for is Main.

**Comment by ketdougi** [comment]
Is it okay to merge this branch now then or should I leave it open till the other tests are added?

**Comment by OwenBC** [comment]
> Is it okay to merge this branch now then or should I leave it open till the other tests are added?

Yeah, I'll add the TreadController tests in a different PR. I'll just do a quick review.

**Comment by OwenBC** [comment]
I'm still making some fixes, the approval was from Jai earlier before any code changes. I'm going to revert the merge and add changes before it's merged to master.

**Comment by OwenBC** [comment]
@ketdougi Could you please approve this so it can be merged #14

**Comment by ketdougi** [comment]
> @ketdougi Could you please approve this so it can be merged #14

I can't review this pull request

**Comment by ketdougi** [comment]
> @ketdougi Could you please approve this so it can be merged #14

nevermind, found the pull request

**Pull request merged**
