### PR TITLE
Create unit test framework and fix workflow for GUI tests

### LINKED ISSUE #10: Add Tests
Add tests to ensure our new features/bug fixes doesn't break the current functionality

### PR DESCRIPTION
**Pull request by OwenBC**
This branch has an example test set up for the Window class and adds workflow changes to support GUI tests.

### CODE REVIEW

**Comment by OwenBC** [comment]
My test appears to failing in the workflow, looking into it now.

**Comment by OwenBC** [comment]
> My test appears to failing in the workflow, looking into it now.

Update: Issue is that testing box is headless and doesn't support the GUI objects. Looking into xvfb as a potential solution.  Creating a custom box could be another solution.

**Comment by OwenBC** [comment]
XVFB worked! Also added a matrix build

**Review by ketdougi — APPROVED** [review]

**Comment by ketdougi** [comment]
Should i create a new branch to add the tests or continue on this one?

**Comment by OwenBC** [comment]
> Should i create a new branch to add the tests or continue on this one?

New branch, this now has some more general workflow changes I would like to have access to in master.

**Pull request merged**
