### PR TITLE
Added Restart Button and Score

### LINKED ISSUE #4: Add Restart Button

### LINKED ISSUE #5: Score board or game over screen

### PR DESCRIPTION
**Pull request by vijaivir**
Added a `JOptionPane()` that displays player score and contains a restart button.
Closes #4, #5

### CODE REVIEW

**Review by OwenBC — CHANGES_REQUESTED** [review]
Could you merge the the `stopTheGame` method with your `game_over` method? You can also make the Window close in your method to prevent this:

image

**Comment by vijaivir** [comment]
> Could you merge the the `stopTheGame` method with your `game_over` method? You can also make the Window close in your method to prevent this:
> 
> image

Good call. I merged the two methods but I'm I can't figure out how to close the original window.

**Comment by OwenBC** [comment]
I did it

**Review by OwenBC — APPROVED** [review]

**Comment by vijaivir** [comment]
> I did it

You made that look easy! I was really struggling to close the window. Thanks @OwenBC

**Pull request merged**
