### PR TITLE
Pause Functionality

### LINKED ISSUE #6: Add Pause functionality
Add pause button or pause functionality by pressing space bar

### PR DESCRIPTION
**Pull request by ketdougi**
This will allow players to pause game by pressing "ESC" button then rejoin game by clicking button

### CODE REVIEW

**Review by vijaivir — DISMISSED** [review]

**Comment by OwenBC** [comment]
@ketdougi are you still working on this?

**Comment by ketdougi** [comment]
> @ketdougi are you still working on this?

yes, I still have to fix some things with the pop up and get the snake to pause it’s movement

**Review by vijaivir — COMMENTED** [review]
I just merged my PR onto master so you will have to deal with some conflicts before merging I think.

**Review by OwenBC — APPROVED** [review]
Looks good

**Pull request merged**
